---
title: "Facebook粉絲團分析（分析專頁名稱朱立倫）"
output: github_document
---
分析朱立倫從2016/01/01到2016/04/09發出的文章。
```{r echo=T}
if (!require('Rfacebook')){
    install.packages("Rfacebook")
    library(Rfacebook)
}
```

## 讀取朱立倫粉絲團資料
```{r echo=T}
token<-'CAACEdEose0cBAH8cf30YKx4eU6SxmZBSGnDMxgqaMuyv4cZCAxtiuZBtJeVJhmZAtZALrZAexD80buXzPhZAaF6TKjnrOCZBjtaqBRZBTY1BcNZAnK1N0kin7ZCH3bTObZC0I01mP8cf8ABrjLmYNUqrzMxk9PqlWU2VVqNPQven7z4EEr6y38hZA4CRA9zW6AmjMaeZBVoZC0CZCnEXhdDSDstZBXEXufMsgTyZB04zYZD'
totalPage<-NULL
lastDate<-Sys.Date()
DateVectorStr<-as.character(seq(as.Date("2016-01-01"),lastDate,by="5 days"))
for(i in 1:(length(DateVectorStr)-1)){
    tempPage<-getPage("llchu", token,
                      since = DateVectorStr[i],until = DateVectorStr[i+1])
    totalPage<-rbind(totalPage,tempPage)
}
nrow(totalPage)
```
發現立倫今年起到04/09共發了129篇文章!

## 每日發文數分析

發現在2016/01/12那天發文數是最多次的，可能是因為靠近01/16選舉日那天了，多多提倡大家來投票，也順便發了幾篇在拜票過成的感觸。
```{r echo=T}
totalPage$datetime <- as.POSIXct(totalPage$created_time, 
                                 format = "%Y-%m-%dT%H:%M:%S+0000", 
                                 tz = "GMT") #2016-01-16T15:05:36+0000
totalPage$dateTPE <- format(totalPage$datetime, "%Y-%m-%d", 
                            tz = "Asia/Taipei") #2016-01-16
totalPage$weekdays <-weekdays(as.Date(totalPage$dateTPE))
PostCount<-aggregate(id~dateTPE,totalPage,length)
library(knitr)
kable(head(PostCount[order(PostCount$id,decreasing = T),]))
```


## 每日獲得讚數分析

分析後發現2016/01/16，也就是大選當天po的文章讚數平均有高達8萬個!!
平均讚數最高的第2名是02/06那天Po的一篇文章，內容是新北市派出30為特搜大隊去台南幫忙救災!!!!!!!!
果然~感人的舉動只要一篇就能獲得廣大的讚。

```{r echo=T}
totalPage$datetime <- as.POSIXct(totalPage$created_time, 
                                 format = "%Y-%m-%dT%H:%M:%S+0000", 
                                 tz = "GMT") #2016-01-16T15:05:36+0000
totalPage$dateTPE <- format(totalPage$datetime, "%Y-%m-%d", 
                            tz = "Asia/Taipei") #2016-01-16
totalPage$weekdays <-weekdays(as.Date(totalPage$dateTPE))
LikeCount<-aggregate(likes_count~dateTPE,totalPage,mean)
library(knitr)
kable(head(LikeCount[order(LikeCount$likes_count,decreasing = T),]))
```

##每日評論數分析

評論數最高的前幾名也都是大選前幾天!!可見大家都有很多的話想要跟朱立倫說~

```{r echo=T}
totalPage$datetime <- as.POSIXct(totalPage$created_time, 
                                 format = "%Y-%m-%dT%H:%M:%S+0000", 
                                 tz = "GMT") #2016-01-16T15:05:36+0000
totalPage$dateTPE <- format(totalPage$datetime, "%Y-%m-%d", 
                            tz = "Asia/Taipei") #2016-01-16
totalPage$weekdays <-weekdays(as.Date(totalPage$dateTPE))
CommentsCount<-aggregate(comments_count~dateTPE,totalPage,mean)
library(knitr)
kable(head(CommentsCount[order(CommentsCount$comments_count,decreasing = T),]))
```

##每日分享數分析

在大選前日感覺大家都動員起來，為朱立倫宣傳他的理念，想讓更多人看到。

```{r echo=T}
totalPage$datetime <- as.POSIXct(totalPage$created_time, 
                                 format = "%Y-%m-%dT%H:%M:%S+0000", 
                                 tz = "GMT") #2016-01-16T15:05:36+0000
totalPage$dateTPE <- format(totalPage$datetime, "%Y-%m-%d", 
                            tz = "Asia/Taipei") #2016-01-16
totalPage$weekdays <-weekdays(as.Date(totalPage$dateTPE))
SharesCount<-aggregate(shares_count~dateTPE,totalPage,mean)
library(knitr)
kable(head(SharesCount[order(SharesCount$shares_count,decreasing = T),]))
```
