---
title: "Hotel"
output: html_document
---
```{r echo=T}
library("jsonlite")
Hotel_data <- fromJSON("http://data.taipei.gov.tw/opendata/apply/query/NDQxOEM2MDAtRDdGNS00NkQ2LUJCMUYtMURBMjlEQUI5MUU5?$format=json")
head(Hotel_data)
```

```{r echo=T}

library(reshape2)
Hotel_data.m <- melt(Hotel_data,id.vars = c('cat1','cat2','stitle','address'))
head(Hotel_data.m)
```

#雙北市住宿分類
```{r echo=T}
aggregate(Hotel_data.m$cat2,by=list(Hotel_data.m$cat2),FUN=length)
#第一個欄位是未分類的數量，每個數字加總就是雙北市總共的旅館數
```
##台北市住宿分類
```{r echo=T}
Taipei <-Hotel_data.m[grep("臺北市",Hotel_data.m$address),]
aggregate(Taipei$cat2,by=list(Taipei$cat2),FUN=length)

```
台北市 中正區
```{r echo=T}
Taipei.100 <-Taipei[grep("中正區",Taipei$address),]
aggregate(Taipei.100$cat2,by=list(Taipei.100$cat2),FUN=length)
```
台北市 大同區
```{r echo=T}
Taipei.103 <-Taipei[grep("大同區",Taipei$address),]
aggregate(Taipei.103$cat2,by=list(Taipei.103$cat2),FUN=length)

```
台北市 中山區
```{r echo=T}
Taipei.104 <-Taipei[grep("中山區",Taipei$address),]
aggregate(Taipei.104$cat2,by=list(Taipei.104$cat2),FUN=length)

```
台北市 松山區
```{r echo=T}
Taipei.105 <-Taipei[grep("松山區",Taipei$address),]
aggregate(Taipei.105$cat2,by=list(Taipei.105$cat2),FUN=length)

```
台北市 大安區
```{r echo=T}
Taipei.106 <-Taipei[grep("大安區",Taipei$address),]
aggregate(Taipei.106$cat2,by=list(Taipei.106$cat2),FUN=length)

```
台北市 萬華區
```{r echo=T}
Taipei.108 <-Taipei[grep("萬華區",Taipei$address),]
aggregate(Taipei.108$cat2,by=list(Taipei.108$cat2),FUN=length)
```
台北市 信義區
```{r echo=T}
Taipei.110 <-Taipei[grep("信義區",Taipei$address),]
aggregate(Taipei.110$cat2,by=list(Taipei.110$cat2),FUN=length)
```
台北市 士林區
```{r echo=T}
Taipei.111 <-Taipei[grep("士林區",Taipei$address),]
aggregate(Taipei.111$cat2,by=list(Taipei.111$cat2),FUN=length)
```
台北市 北投區
```{r echo=T}
Taipei.112 <-Taipei[grep("北投區",Taipei$address),]
aggregate(Taipei.112$cat2,by=list(Taipei.112$cat2),FUN=length)
```
台北市 內湖區
```{r echo=T}
Taipei.114 <-Taipei[grep("內湖區",Taipei$address),]
aggregate(Taipei.114$cat2,by=list(Taipei.114$cat2),FUN=length)
```
台北市 南港區
```{r echo=T}
Taipei.115 <-Taipei[grep("南港區",Taipei$address),]
aggregate(Taipei.115$cat2,by=list(Taipei.115$cat2),FUN=length)
```
台北市 文山區
```{r echo=T}
Taipei.116 <-Taipei[grep("文山區",Taipei$address),]
aggregate(Taipei.116$cat2,by=list(Taipei.116$cat2),FUN=length)
```

##新北市住宿分類(發現他們都沒有分類ex:一般旅館,一般觀光旅館...)
```{r echo=T}
NEW_Taipei <-Hotel_data.m[grep("新北市",Hotel_data.m$address),]
aggregate(NEW_Taipei$cat2,by=list(NEW_Taipei$cat2),FUN=length)
```


新北市 萬里區
```{r echo=T}
NEW_Taipei.207 <-NEW_Taipei[grep("萬里區",NEW_Taipei$address),]
aggregate(NEW_Taipei.207$cat2,by=list(NEW_Taipei.207$cat2),FUN=length)
```
新北市 金山區
```{r echo=T}
NEW_Taipei.208 <-NEW_Taipei[grep("金山區",NEW_Taipei$address),]
aggregate(NEW_Taipei.208$cat2,by=list(NEW_Taipei.208$cat2),FUN=length)
```
新北市 板橋區
```{r echo=T}
NEW_Taipei.220 <-NEW_Taipei[grep("板橋區",NEW_Taipei$address),]
aggregate(NEW_Taipei.220$cat2,by=list(NEW_Taipei.220$cat2),FUN=length)
```
新北市 汐止區
```{r echo=T}
NEW_Taipei.221 <-NEW_Taipei[grep("汐止區",NEW_Taipei$address),]
aggregate(NEW_Taipei.221 $cat2,by=list(NEW_Taipei.221 $cat2),FUN=length)
```
新北市 深坑區
```{r echo=T}
NEW_Taipei.222 <-NEW_Taipei[grep("深坑區",NEW_Taipei$address),]
aggregate(NEW_Taipei.222$cat2,by=list(NEW_Taipei.222$cat2),FUN=length)
```
新北市 石碇區
```{r echo=T}
NEW_Taipei.223 <-NEW_Taipei[grep("石碇區",NEW_Taipei$address),]
aggregate(NEW_Taipei.223$cat2,by=list(NEW_Taipei.223$cat2),FUN=length)
```
新北市 瑞芳區
```{r echo=T}
NEW_Taipei.224 <-NEW_Taipei[grep("瑞芳區",NEW_Taipei$address),]
aggregate(NEW_Taipei.224$cat2,by=list(NEW_Taipei.224$cat2),FUN=length)
```
新北市 平溪區
```{r echo=T}
NEW_Taipei.226 <-NEW_Taipei[grep("平溪區",NEW_Taipei$address),]
aggregate(NEW_Taipei.226$cat2,by=list(NEW_Taipei.226$cat2),FUN=length)
```
新北市 雙溪區
```{r echo=T}
NEW_Taipei.227 <-NEW_Taipei[grep("雙溪區",NEW_Taipei$address),]
aggregate(NEW_Taipei.227$cat2,by=list(NEW_Taipei.227$cat2),FUN=length)
```
新北市 貢寮區
```{r echo=T}
NEW_Taipei.228 <-NEW_Taipei[grep("貢寮區",NEW_Taipei$address),]
aggregate(NEW_Taipei.228$cat2,by=list(NEW_Taipei.228$cat2),FUN=length)
```
新北市 新店區
```{r echo=T}
NEW_Taipei.231 <-NEW_Taipei[grep("新店區",NEW_Taipei$address),]
aggregate(NEW_Taipei.231$cat2,by=list(NEW_Taipei.231$cat2),FUN=length)
```
新北市 坪林區
```{r echo=T}
NEW_Taipei.232 <-NEW_Taipei[grep("坪林區",NEW_Taipei$address),]
NEW_Taipei.232
```
新北市 烏來區
```{r echo=T}
NEW_Taipei.233 <-NEW_Taipei[grep("烏來區",NEW_Taipei$address),]
aggregate(NEW_Taipei.233$cat2,by=list(NEW_Taipei.233$cat2),FUN=length)
```
新北市 永和區
```{r echo=T}
NEW_Taipei.234 <-NEW_Taipei[grep("永和區",NEW_Taipei$address),]
aggregate(NEW_Taipei.234$cat2,by=list(NEW_Taipei.234$cat2),FUN=length)
```
新北市 中和區
```{r echo=T}
NEW_Taipei.235 <-NEW_Taipei[grep("中和區",NEW_Taipei$address),]
aggregate(NEW_Taipei.235$cat2,by=list(NEW_Taipei.235$cat2),FUN=length)
```
新北市 土城區
```{r echo=T}
NEW_Taipei.236 <-NEW_Taipei[grep("土城區",NEW_Taipei$address),]
aggregate(NEW_Taipei.236$cat2,by=list(NEW_Taipei.236$cat2),FUN=length)
```
新北市 三峽區
```{r echo=T}
NEW_Taipei.237 <-NEW_Taipei[grep("三峽區",NEW_Taipei$address),]
aggregate(NEW_Taipei.237$cat2,by=list(NEW_Taipei.237$cat2),FUN=length)
```
新北市 樹林區
```{r echo=T}
NEW_Taipei.238 <-NEW_Taipei[grep("樹林區",NEW_Taipei$address),]
aggregate(NEW_Taipei.238$cat2,by=list(NEW_Taipei.238$cat2),FUN=length)
```
新北市 鶯歌區
```{r echo=T}
NEW_Taipei.239 <-NEW_Taipei[grep("鶯歌區",NEW_Taipei$address),]
aggregate(NEW_Taipei.239$cat2,by=list(NEW_Taipei.239$cat2),FUN=length)
```
新北市 三重區
```{r echo=T}
NEW_Taipei.241 <-NEW_Taipei[grep("三重區",NEW_Taipei$address),]
aggregate(NEW_Taipei.241$cat2,by=list(NEW_Taipei.241$cat2),FUN=length)
```
新北市 新莊區
```{r echo=T}
NEW_Taipei.242 <-NEW_Taipei[grep("新莊區",NEW_Taipei$address),]
aggregate(NEW_Taipei.242$cat2,by=list(NEW_Taipei.242$cat2),FUN=length)
```
新北市 泰山區
```{r echo=T}
NEW_Taipei.243 <-NEW_Taipei[grep("泰山區",NEW_Taipei$address),]
aggregate(NEW_Taipei.243$cat2,by=list(NEW_Taipei.243$cat2),FUN=length)
```
新北市 林口區
```{r echo=T}
NEW_Taipei.244 <-NEW_Taipei[grep("林口區",NEW_Taipei$address),]
aggregate(NEW_Taipei.244$cat2,by=list(NEW_Taipei.244$cat2),FUN=length)
```
新北市 蘆洲區
```{r echo=T}
NEW_Taipei.247 <-NEW_Taipei[grep("蘆洲區",NEW_Taipei$address),]
aggregate(NEW_Taipei.247$cat2,by=list(NEW_Taipei.247$cat2),FUN=length)
```
新北市 五股區
```{r echo=T}
NEW_Taipei.248 <-NEW_Taipei[grep("五股區",NEW_Taipei$address),]
aggregate(NEW_Taipei.248$cat2,by=list(NEW_Taipei.248$cat2),FUN=length)
```
新北市 八里區
```{r echo=T}
NEW_Taipei.249 <-NEW_Taipei[grep("八里區",NEW_Taipei$address),]
aggregate(NEW_Taipei.249$cat2,by=list(NEW_Taipei.249$cat2),FUN=length)
```
新北市 淡水區
```{r echo=T}
NEW_Taipei.251 <-NEW_Taipei[grep("淡水區",NEW_Taipei$address),]
aggregate(NEW_Taipei.251$cat2,by=list(NEW_Taipei.251$cat2),FUN=length)
```
新北市 三芝區
```{r echo=T}
NEW_Taipei.252 <-NEW_Taipei[grep("三芝區",NEW_Taipei$address),]
aggregate(NEW_Taipei.252$cat2,by=list(NEW_Taipei.252$cat2),FUN=length)
```
新北市 石門區
```{r echo=T}
NEW_Taipei.253 <-NEW_Taipei[grep("石門區",NEW_Taipei$address),]
aggregate(NEW_Taipei.253$cat2,by=list(NEW_Taipei.253$cat2),FUN=length)
```

